# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  vmhost:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /tmp/procudo
  container:
    docker:
      - image: circleci/python:3.7.4
    working_directory: /tmp/procudo

jobs: 
  init:
    executor: vmhost
    steps:
      - checkout
      - run:
          name: "Install OpenVPN"
          command: |
            sudo apt-get update
            sudo apt-get install openvpn
      - run:
          name: "Install CFSSL"
          command: |
            cd /tmp/
            echo "Installing cfssljson"
            wget https://github.com/cloudflare/cfssl/releases/download/v1.4.1/cfssljson_1.4.1_linux_amd64 -O cfssljson
            sudo mv cfssljson /usr/local/bin/
            sudo chmod +x /usr/local/bin/cfssljson

            echo "Installing cfssl"
            wget https://github.com/cloudflare/cfssl/releases/download/v1.4.1/cfssl_1.4.1_linux_amd64 -O cfssl
            sudo mv cfssl /usr/local/bin/
            sudo chmod +x /usr/local/bin/cfssl
      - run:
          name: "Generate CA, Server and Client Testing Certificates"
          command: |
            mkdir -p data
            cd .cfssl/
            mkdir -p pki/clients
            cfssl genkey --initca conf/openvpn-ca-csr.json | cfssljson -bare pki/ca
            cfssl gencert -ca pki/ca.pem -ca-key pki/ca-key.pem -config conf/openvpn-ca-config.json -profile="server" -hostname="server" conf/openvpn-server-csr.json | cfssljson -bare pki/server
            cfssl gencert -ca pki/ca.pem -ca-key pki/ca-key.pem -config conf/openvpn-ca-config.json -profile="client" -hostname="client" conf/openvpn-client-csr.json | cfssljson -bare pki/clients/client
            openssl genpkey -genparam -algorithm DH -pkeyopt dh_paramgen_prime_len:2048 -out pki/dh2048.pem 
            # openssl genpkey -genparam -algorithm DH -pkeyopt dh_paramgen_prime_len:4096 -out pki/dh4096.pem 
            openvpn --genkey --secret pki/ta.key
            cp -r pki/ ../data/
      - persist_to_workspace:
          root: /tmp/procudo
          paths:
            - .cfssl/pki


  build:
    executor: executor
    steps:  
      - checkout
      - attach_workspace:
          at: /tmp/procudo
      - run:
          name: "Install Build Tools"
          command: |
              curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
              exec $SHELL
              pyenv update

      # - run:
      #     name: "Install Python"
      #     command: |
      #       mkdir -p /tmp/py_install
      #       cd /tmp/py_install
      #       wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz
      #       tar -xf Python-3.7.4.tgz
      #       cd Python-3.7.4
      #       ./configure
      #       make -j 2
      #       sudo make altinstall

      - run:
          name: "Install Dependencies"
          command: |
            pyenv install 3.7.4
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            coverage run tests.py
            coverage report -m procudo
            coverage html
            codecov

      - store_artifacts:
          path: htmlcov
      

workflows:
  version: 2
  workflow:
    jobs:
      - init
      - build:
          requires:
            - init


