# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs: 
  build:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-certificates-{{ checksum ".cfssl/pki/ca.pem" }}
            - v1-certificates-

      - run:
          name: Generate CA, Server and Client Certificates
          command: |
            mkdir -p data
            cd .cfssl/
            ./setup.sh

      - save_cache:
          paths:
            - .cfssl/pki
          key: v1-certificates-{{ checksum ".cfssl/pki/ca.pem" }}

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            coverage run tests.py
            coverage report -m procudo
            coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
